name: ghseet-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy files to folder
        run: |
          cp -r ${{github.workspace}}/* /home/pi/gsheet-notifier-copilot

