# testing runner on new server
# 
name: ghseet-workflow

on:
  push:
    branches:
      - main

env:
  APP_DIR: /home/runneruser/services/ghseet-notify
  SERVICE_NAME: gsheet-monitor.service
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Python virtual environment
        run: |
          cd $APP_DIR
          /usr/bin/python3.11 -m venv venv      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          envkey_RANGE_NAME: ${{ secrets.RANGE_NAME }}
          envkey_POLLING_INTERVAL: ${{ vars.POLLING_INTERVAL }}
          envkey_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          envkey_NOTIFICATION_TOPIC: ${{ vars.NOTIFICATION_TOPIC }}
          file_name: ".env"
          fail_on_empty: false
          sort_keys: false
      - name: Check for .env and copy it
        run: |
          pwd
          ls -la
          cp -r ${{github.workspace}}/.env $APP_DIR
      - name: Copy files to folder
        run: |
          cp -r ${{github.workspace}}/* $APP_DIR

      - name: Install dependencies
        run: |
          cd $APP_DIR
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if service unit file exists
        run: |
          if systemctl list-units --all -t service --full --no-legend "$SERVICE_NAME" | grep -q "$SERVICE_NAME"; then
            echo "Service '$SERVICE_NAME' unit file exists."
            exit 0
          else
            echo "Service '$SERVICE_NAME' unit file does not exist."
            exit 1
          fi
      - name: Execute if success
        if: success()
        run: echo "Service exists, skipping installation."
      - name: Install service if not exists
        if: failure()
        run: |
          # cd $APP_DIR/scripts
          # chmod +x install_service.sh
          # ./install_service.sh
          echo "Service installed."


      - name: Restart Service
        run: |
          sudo systemctl restart gsheet-monitor.service
          sleep 5
          sudo systemctl status gsheet-monitor.service


