# testing runner on new server
# 
name: ghseet-workflow

on:
  push:
    branches:
      - main

env:
  APP_DIR: /home/runneruser/services/ghseet-notify
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Python virtual environment
        run: |
          cd $APP_DIR
          /usr/bin/python3.11 -m venv venv      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          RANGE_NAME: ${{ secrets.RANGE_NAME }}
          POLLING_INTERVAL: ${{ vars.POLLING_INTERVAL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NOTIFICATION_TOPIC: ${{ vars.NOTIFICATION_TOPIC }}
          file_name: ".env"
          fail_on_empty: false
          sort_keys: false
      - name: Check if .env file exists
        run: |
          pwd
          ls -la
      - name: Copy files to folder
        run: |
          cp -r ${{github.workspace}}/* $APP_DIR

      - name: Install dependencies
        run: |
          cd $APP_DIR
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restart Service
        run: |
          sudo systemctl restart gsheet-monitor.service
          sleep 5
          sudo systemctl status gsheet-monitor.service


