# testing runner on new server
# 
name: gsheet-docker-workflow

on: workflow_dispatch

env:
  APP_DIR: /home/runneruser/services/gsheet-notify-docker

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          envkey_RANGE_NAME: ${{ secrets.RANGE_NAME }}
          envkey_POLLING_INTERVAL: ${{ vars.POLLING_INTERVAL }}
          envkey_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          envkey_NOTIFICATION_TOPIC: ${{ vars.NOTIFICATION_TOPIC }}
          file_name: ".env"
          fail_on_empty: false
          sort_keys: false

      - name: Check for .env and copy it
        run: |
          pwd
          ls -la
          cp -r ${{github.workspace}}/.env $APP_DIR

      - name: Copy files to folder
        run: |
          cp -r ${{github.workspace}}/* $APP_DIR

      - name: Build and Run Docker Container
        run: |
          cd ${{env.APP_DIR}}
          docker compose build --label "url=${{ vars.WEBSITE_URL }}"
          docker compose up -d


